server.port=${SERVER_PORT:8080}

spring.application.name=guardian-financiero-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:guardian_financiero_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${JWT_SECRET:clave_super_secreta_para_desarrollo_guardian_financiero_ia_2026}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
