-- init.sql
-- =========================================================================
-- IMPORTANTE: PostgreSQL no permite ejecutar 'CREATE DATABASE' fácilmente
-- dentro de una misma conexión si la base de datos ya está en uso o si 
-- el script se corre dentro de una transacción.
--
-- Para crear la base de datos por primera vez, conéctate a 'postgres' y ejecuta:
-- CREATE DATABASE guardian_financiero_db;
--
-- Si la base de datos guardian_financiero_db ya existe, ignora la línea anterior.
-- =========================================================================

-- Las tablas (users, customers, transactions, fraud_alerts, risk_rules,
-- audit_logs, ai_analysis) se generarán automáticamente gracias a Spring Boot
-- y la propiedad spring.jpa.hibernate.ddl-auto=update.
